apiVersion: v1
kind: PersistentVolume
metadata:
  name: am-connector--volume
  namespace: test-namespace
spec:
  storageClassName: am-connector--volume--nfs
  capacity:
    storage: 1500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: '/connector'
    server: am-tier-nfs.am-space
